// Design tokens — single source of truth
export const C = {
  brand:   "#C8321A",
  brandBg: "#fef2f0",
  text:    "#111827",
  textSub: "#6b7280",
  textMuted:"#9ca3af",
  border:  "#e5e7eb",
  borderLight:"#f3f4f6",
  bg:      "#f7f6f3",
  surface: "#ffffff",
  green:   "#059669",
  greenBg: "#dcfce7",
  greenTx: "#166534",
  amber:   "#d97706",
  amberBg: "#fef3c7",
  amberTx: "#92400e",
  red:     "#dc2626",
  redBg:   "#fee2e2",
  redTx:   "#991b1b",
  blue:    "#2563eb",
  blueBg:  "#dbeafe",
  blueTx:  "#1e40af",
  violet:  "#7c3aed",
  violetBg:"#ede9fe",
  violetTx:"#4c1d95",
};

export const S = {
  card: {
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    padding: 16,
  } as React.CSSProperties,
  cardNoPad: {
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    overflow: "hidden",
  } as React.CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: C.textMuted,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    marginBottom: 12,
  } as React.CSSProperties,
  badge: (bg: string, color: string): React.CSSProperties => ({
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: 100,
    fontSize: 11,
    fontWeight: 500,
    background: bg,
    color,
    lineHeight: "1.6",
    whiteSpace: "nowrap",
  }),
};
